sudo: false
language: scala
scala:
  - 2.11.8
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
notifications:
  slack: outr:A8tndkIibmnKjv7YBMnAK7SE
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean scribeJS/test
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage scribeJVM/test slf4j/test
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport
  - sbt ++$TRAVIS_SCALA_VERSION coverageAggregate
  - sbt ++$TRAVIS_SCALA_VERSION codacyCoverage